"use client";

import { useDeferredValue, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { AlertCircle, Armchair, BusFront, Loader2, Plus, Search, ShieldCheck, UserRound, X } from "lucide-react";
import { useSession } from "@/components/layout/session-context";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useBuses, useCreateBus, useCreateDriver, useCreateSeatTemplate, useDrivers, useSeatTemplates, useUpdateBus, useUpdateDriver } from "../hooks/use-fleet";
import type { BusStatus, DriverStatus, SeatTemplate } from "../types";

const selectClass = "h-10 w-full rounded-xl border border-input bg-card px-3 text-sm shadow-sm focus-visible:border-primary/50 focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/10";
const statusLabel: Record<BusStatus, string> = { READY: "جاهزة", MAINTENANCE: "صيانة", OUT_OF_SERVICE: "خارج الخدمة" };
const driverStatusLabel: Record<DriverStatus, string> = { ACTIVE: "نشط", INACTIVE: "غير نشط", SUSPENDED: "موقوف" };

export function FleetFeature() {
  const user = useSession();
  const canManage = user.permissions.includes("*") || user.permissions.includes("fleet.write");
  const [tab, setTab] = useState("buses");
  const [modal, setModal] = useState<"bus" | "driver" | "template" | null>(null);
  const [search, setSearch] = useState("");
  const deferredSearch = useDeferredValue(search);
  const buses = useBuses();
  const templates = useSeatTemplates();
  const drivers = useDrivers(tab === "drivers" ? deferredSearch : "");
  const updateBus = useUpdateBus();
  const updateDriver = useUpdateDriver();
  const visibleBuses = useMemo(() => buses.data?.filter((bus) => `${bus.plateNumber} ${bus.model ?? ""}`.toLowerCase().includes(search.toLowerCase())), [buses.data, search]);

  const actions = tab === "buses" ? { label: "إضافة حافلة", type: "bus" as const } : tab === "drivers" ? { label: "إضافة سائق", type: "driver" as const } : { label: "إضافة قالب", type: "template" as const };

  return (
    <div className="mx-auto max-w-[96rem] space-y-6">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1.5 text-xs font-bold text-primary">إدارة الأصول</p><h1 className="font-display text-2xl font-bold sm:text-3xl">الأسطول والسائقون</h1><p className="mt-2 text-sm text-muted-foreground">راقب جاهزية الحافلات وصلاحية السائقين وقوالب المقاعد.</p></div>{canManage ? <Button onClick={() => setModal(actions.type)}><Plus />{actions.label}</Button> : null}</div>

      <Tabs value={tab} onValueChange={setTab} dir="rtl"><TabsList><TabsTrigger value="buses">الحافلات</TabsTrigger><TabsTrigger value="drivers">السائقون</TabsTrigger><TabsTrigger value="templates">قوالب المقاعد</TabsTrigger></TabsList>
        <div className="mt-5 max-w-md"><div className="relative"><Search className="absolute right-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pr-9" placeholder="ابحث في السجل..." value={search} onChange={(event) => setSearch(event.target.value)} /></div></div>
        <TabsContent value="buses" className="mt-5"><LoadingState query={buses}>{visibleBuses?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleBuses.map((bus) => <Card key={bus.id} className="overflow-hidden"><CardContent className="p-5"><div className="flex items-start justify-between"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><BusFront /></span><Badge variant={bus.status === "READY" ? "success" : bus.status === "MAINTENANCE" ? "warning" : "destructive"}>{statusLabel[bus.status]}</Badge></div><h2 className="mt-4 font-display text-lg font-semibold" dir="ltr">{bus.plateNumber}</h2><p className="text-sm text-muted-foreground">{bus.model ?? "موديل غير محدد"}{bus.year ? ` · ${bus.year}` : ""}</p><div className="mt-4 flex items-center justify-between rounded-xl bg-muted/60 p-3 text-xs"><span>{bus.seatTemplate.name}</span><strong>{bus.seatTemplate.rows * bus.seatTemplate.columnsPerRow} مقعدًا</strong></div>{canManage ? <select className={`${selectClass} mt-4`} value={bus.status} disabled={updateBus.isPending} onChange={(event) => updateBus.mutate({ id: bus.id, input: { status: event.target.value as BusStatus } })}>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : null}</CardContent></Card>)}</div> : <EmptyState icon={<BusFront className="h-9 w-9" />} title="لا توجد حافلات" description="أضف أول حافلة إلى الأسطول." />}</LoadingState></TabsContent>
        <TabsContent value="drivers" className="mt-5"><LoadingState query={drivers}>{drivers.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{drivers.data.map((driver) => { const expired = new Date(driver.licenseExpiry) < new Date(); return <Card key={driver.id}><CardContent className="p-5"><div className="flex items-start justify-between"><span className="rounded-2xl bg-blue-500/10 p-3 text-blue-600"><UserRound /></span><Badge variant={expired ? "destructive" : driver.status === "ACTIVE" ? "success" : "secondary"}>{expired ? "الرخصة منتهية" : driverStatusLabel[driver.status]}</Badge></div><h2 className="mt-4 font-display font-semibold">{driver.name}</h2><p className="mt-1 text-sm text-muted-foreground" dir="ltr">{driver.phone}</p><div className="mt-4 space-y-2 rounded-xl bg-muted/60 p-3 text-xs"><p className="flex justify-between"><span className="text-muted-foreground">رقم الرخصة</span><strong>{driver.licenseNumber}</strong></p><p className="flex justify-between"><span className="text-muted-foreground">انتهاء الرخصة</span><strong>{new Intl.DateTimeFormat("ar-SD").format(new Date(driver.licenseExpiry))}</strong></p><p className="flex justify-between"><span className="text-muted-foreground">الرحلات</span><strong>{driver._count.trips}</strong></p></div>{canManage ? <select className={`${selectClass} mt-4`} value={driver.status} disabled={updateDriver.isPending} onChange={(event) => updateDriver.mutate({ id: driver.id, input: { status: event.target.value as DriverStatus } })}>{Object.entries(driverStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : null}</CardContent></Card>; })}</div> : <EmptyState icon={<UserRound className="h-9 w-9" />} title="لا يوجد سائقون" description="أضف السائقين واربطهم بالرحلات." />}</LoadingState></TabsContent>
        <TabsContent value="templates" className="mt-5"><LoadingState query={templates}>{templates.data?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{templates.data.map((template) => <TemplateCard key={template.id} template={template} />)}</div> : <EmptyState icon={<Armchair className="h-9 w-9" />} title="لا توجد قوالب" description="أنشئ تخطيط المقاعد الأول." />}</LoadingState></TabsContent>
      </Tabs>

      {modal ? <Modal title={actions.label} onClose={() => setModal(null)}>{modal === "bus" ? <BusForm templates={templates.data ?? []} onDone={() => setModal(null)} /> : modal === "driver" ? <DriverForm onDone={() => setModal(null)} /> : <TemplateForm onDone={() => setModal(null)} />}</Modal> : null}
    </div>
  );
}

function LoadingState({ query, children }: { query: { isLoading: boolean; isError: boolean }; children: ReactNode }) { if (query.isLoading) return <div className="grid gap-4 md:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-64" />)}</div>; if (query.isError) return <EmptyState icon={<AlertCircle className="h-9 w-9" />} title="تعذر تحميل البيانات" description="أعد تحميل الصفحة أو تحقق من الاتصال." />; return children; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label={title}><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border bg-card p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-lg font-semibold">{title}</h2><Button variant="ghost" size="icon" onClick={onClose}><X /></Button></div>{children}</div></div>; }
function BusForm({ templates, onDone }: { templates: SeatTemplate[]; onDone: () => void }) { const mutation=useCreateBus(); const [form,setForm]=useState({plateNumber:"",model:"",year:"",seatTemplateId:"",status:"READY" as BusStatus}); function submit(e:FormEvent){e.preventDefault();mutation.mutate({plateNumber:form.plateNumber.trim(),model:form.model.trim()||undefined,year:form.year?Number(form.year):undefined,seatTemplateId:form.seatTemplateId,status:form.status},{onSuccess:onDone});} return <form onSubmit={submit} className="space-y-4"><Field label="رقم اللوحة"><Input value={form.plateNumber} onChange={e=>setForm({...form,plateNumber:e.target.value})} required maxLength={30} dir="ltr" /></Field><Field label="الموديل"><Input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} maxLength={100} /></Field><div className="grid grid-cols-2 gap-3"><Field label="سنة الصنع"><Input type="number" min="1900" max="2100" value={form.year} onChange={e=>setForm({...form,year:e.target.value})} /></Field><Field label="الحالة"><select className={selectClass} value={form.status} onChange={e=>setForm({...form,status:e.target.value as BusStatus})}>{Object.entries(statusLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field></div><Field label="قالب المقاعد"><select className={selectClass} value={form.seatTemplateId} onChange={e=>setForm({...form,seatTemplateId:e.target.value})} required><option value="">اختر القالب</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Submit mutation={mutation} /></form>; }
function DriverForm({ onDone }: { onDone: () => void }) { const mutation=useCreateDriver(); const [form,setForm]=useState({name:"",phone:"",licenseNumber:"",licenseExpiry:""}); function submit(e:FormEvent){e.preventDefault();mutation.mutate({...form,licenseExpiry:new Date(form.licenseExpiry).toISOString()},{onSuccess:onDone});} return <form onSubmit={submit} className="space-y-4"><Field label="اسم السائق"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /></Field><Field label="رقم الهاتف"><Input type="tel" dir="ltr" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} required /></Field><Field label="رقم الرخصة"><Input value={form.licenseNumber} onChange={e=>setForm({...form,licenseNumber:e.target.value})} required /></Field><Field label="تاريخ انتهاء الرخصة"><Input type="date" value={form.licenseExpiry} onChange={e=>setForm({...form,licenseExpiry:e.target.value})} required /></Field><Submit mutation={mutation} /></form>; }
function TemplateForm({ onDone }: { onDone: () => void }) { const mutation=useCreateSeatTemplate(); const [form,setForm]=useState({name:"",rows:"10",columnsPerRow:"4",aisleAfterColumn:"2"}); function submit(e:FormEvent){e.preventDefault();mutation.mutate({name:form.name.trim(),rows:Number(form.rows),columnsPerRow:Number(form.columnsPerRow),aisleAfterColumn:Number(form.aisleAfterColumn)},{onSuccess:onDone});} return <form onSubmit={submit} className="space-y-4"><Field label="اسم القالب"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required /></Field><div className="grid grid-cols-3 gap-3"><Field label="الصفوف"><Input type="number" min="1" max="50" value={form.rows} onChange={e=>setForm({...form,rows:e.target.value})} required /></Field><Field label="الأعمدة"><Input type="number" min="1" max="10" value={form.columnsPerRow} onChange={e=>setForm({...form,columnsPerRow:e.target.value})} required /></Field><Field label="الممر بعد"><Input type="number" min="0" value={form.aisleAfterColumn} onChange={e=>setForm({...form,aisleAfterColumn:e.target.value})} required /></Field></div><Submit mutation={mutation} /></form>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block space-y-2"><span className="text-sm font-medium">{label}</span>{children}</label>; }
function Submit({ mutation }: { mutation: { isPending: boolean; isError: boolean; error: Error | null } }) { return <div className="space-y-3 pt-2">{mutation.isError ? <p className="text-sm text-destructive">{mutation.error?.message}</p> : null}<Button className="w-full" type="submit" disabled={mutation.isPending}>{mutation.isPending ? <Loader2 className="animate-spin" /> : <ShieldCheck />}حفظ البيانات</Button></div>; }
function TemplateCard({ template }: { template: SeatTemplate }) { return <Card><CardContent className="p-5"><div className="flex items-start justify-between"><span className="rounded-2xl bg-violet-500/10 p-3 text-violet-600"><Armchair /></span><Badge variant="secondary">{template._count?.buses ?? 0} حافلة</Badge></div><h2 className="mt-4 font-display font-semibold">{template.name}</h2><p className="mt-1 text-sm text-muted-foreground">{template.rows} صفوف · {template.columnsPerRow} مقاعد في الصف</p><div className="mt-4 grid gap-1.5 rounded-2xl bg-muted/50 p-3" style={{gridTemplateColumns:`repeat(${template.columnsPerRow + 1},minmax(0,1fr))`}}>{template.seats.slice(0,Math.min(template.seats.length,20)).map(seat=><span key={seat.id} className="flex h-6 items-center justify-center rounded-md border bg-card text-[8px] text-muted-foreground" style={{gridColumn:seat.column>template.aisleAfterColumn?seat.column+1:seat.column}}>{seat.label}</span>)}</div></CardContent></Card>; }
